# Generated by Django 4.2.13 on 2024-07-08 19:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcessingTasks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("processing", "Processing"),
                            ("failed", "Failed"),
                            ("Completed", "Completed"),
                        ],
                        default="processing",
                        max_length=20,
                    ),
                ),
                ("video_path", models.CharField(max_length=520)),
            ],
        ),
    ]
